Fixes-UVU-101
pcridesagain/2620-fall-23 pull request #103
Opened 2023-10-13 03:18 UTC by Jchart3

<img width="1349" alt="Screenshot 2023-10-12 at 8 26 43 PM" src="https://github.com/pcridesagain/2620-fall-23/assets/143059647/3d8c4070-91d1-42bc-8431-1f7e1ae2f8e6">

2023-10-26 05:31 UTC, pcridesagain requested changes
Neato! I do have one change request, it might be easier if we chat in class, but I think you can put all of your (button, button2... paragraph, paragraph2... tab) into one component file, set some vars and props, and then when you create an instance of the component you are just using 1 HTML tag with defined properties like "tab number" or something. You can follow the in class example, but like I said, might be easier to explain myself in class. https://svelte.dev/repl/f9aba0f00a93443e98d0f107770d41ac?version=4.2.1

2023-11-03 00:09 UTC, Jchart3 reviewed
updated svelte component

2023-11-03 01:36 UTC, Mike-Dahle approved these changes

2023-11-03 01:36 UTC, alejandragarcia9 approved these changes

2023-11-03 01:37 UTC, Fernn10 approved these changes
Looks good!

2023-11-03 01:45 UTC, merged