UVU-104-Svelte-Component
pcridesagain/2620-fall-23 pull request #107
Opened 2023-10-16 17:36 UTC by Mike-Dahle

Fixes UVU-104
<img width="851" alt="Screen Shot 2023-10-16 at 11 35 50 AM" src="https://github.com/pcridesagain/2620-fall-23/assets/91270944/b25375d8-8eee-4fa8-a4a5-8f9b242f7657">

2023-10-26 05:41 UTC, pcridesagain requested changes
Looking good. I do have one change request. Would be super cool to create one button component file (button.svelte) using a variables and if statements to define the sizes, then add a prop to set why size of button you want when you create an instance of the button inside your app, you can follow the in class example to see how this would work with your component (look at button.svelte) https://svelte.dev/repl/f9aba0f00a93443e98d0f107770d41ac?version=4.2.1

2023-10-27 18:30 UTC, Mike-Dahle commented
Changed my buttons to be one component with passed props and I added a hover color as well

2023-11-03 01:41 UTC, pcridesagain approved these changes

2023-11-03 01:43 UTC, addilewis21 approved these changes
nice!

2023-11-03 01:44 UTC, Jchart3 approved these changes

2023-11-03 01:45 UTC, merged