UVU-106
pcridesagain/2620-fall-23 pull request #87
Opened 2023-10-12 23:39 UTC by DocSmudge

Fixes UVU-106
![Screenshot 2023-10-12 at 5 38 46 PM](https://github.com/pcridesagain/2620-fall-23/assets/91097394/5d202878-03cf-426d-9edf-4bb793caf8dc)

2023-10-19 01:26 UTC, allison-baker approved these changes
I think the blue circle is supposed to be a different shade on light vs dark mode. We're also only doing dark mode, you don't need light. And is the blue circle supposed to be on the hover state or when the date is selected?

2023-10-26 05:51 UTC, pcridesagain requested changes
This is fantastic! You got stuck with the table layout component! I do have one (maybe minor) change request, it might be easier to chat about in class, but it would be super rad if you were to dump all that CSS and use Tailwind classes, I think we can do that with a simple IF statement, but lets chat in class about it and see if it makes sense.

2023-11-03 02:41 UTC, DocSmudge commented
> This is fantastic! You got stuck with the table layout component! I do have one (maybe minor) change request, it might be easier to chat about in class, but it would be super rad if you were to dump all that CSS and use Tailwind classes, I think we can do that with a simple IF statement, but lets chat in class about it and see if it makes sense.

Just updated my code. Awaiting a review.

2023-11-03 15:10 UTC, pcridesagain approved these changes

2023-11-03 15:36 UTC, merged