Svelte component UVU-122
pcridesagain/2620-fall-23 pull request #91
Opened 2023-10-13 00:48 UTC by hoyin12440

Adding Svelte component files

2023-10-13 02:40 UTC, willmiles00 approved these changes
Let's get this bread!

2023-10-13 04:56 UTC, X1Warrior reviewed
Is this for the svelte component or the tailwind component?

2023-10-26 07:17 UTC, pcridesagain requested changes
I think we might have the wrong branch or PR, let's chat in class and figure it out.

2023-11-03 15:34 UTC, pcridesagain approved these changes

2023-11-03 15:34 UTC, merged