Fixes UVU-116
pcridesagain/2620-fall-23 pull request #95
Opened 2023-10-13 02:35 UTC by willmiles00

<img width="756" alt="Screenshot 2023-10-12 at 8 34 13 PM" src="https://github.com/pcridesagain/2620-fall-23/assets/113927655/f678b362-dd0c-47a3-b756-0189e82e9273">

2023-10-13 04:57 UTC, X1Warrior approved these changes
A lot to put into one commit, but good job!

2023-10-26 06:50 UTC, pcridesagain requested changes
This is so broken.... JK JK JK. It's really so close. But what happens when I need to change the text of the popup? To make it truly resusable, you'll need to make it so you can define the words when creating the instance of the component. Let's discuss in class - I have ideas.

2023-11-02 17:57 UTC, gabbepond approved these changes
Fail Jk haha Looking good

2023-11-03 01:38 UTC, Mike-Dahle approved these changes

2023-11-03 15:34 UTC, pcridesagain approved these changes

2023-11-03 15:34 UTC, merged